name: 'nodesampleapp'
namespace: 'xenoss-live'
pci_scope: non_pci
environment: production
mode: live
aws_account: 420361828844
chamber:
  enabled: true
  chamber_region: us-west-2
  kms_key_alias: parameter_store_key
  paths:
    - 'production/live/nodesampleapp'

shared_env:
  NODE_ENV: 'production'
  APP_ENV: 'production'
  APP_MODE: 'live'
  APP_AWS_REGION: 'ap-southeast-1'
  DRY_RUN: 'true'
  CONNECTION_LIMIT: '5'
  PAYMENT_FILTER_DATE_COMPENSATION: '1'

image:
  repository: 420361828844.dkr.ecr.ap-southeast-1.amazonaws.com/xendit/nodesampleapp
  pullPolicy: Always

datadog:
  apm:
    enabled: true

server:
  enabled: true
  public:
    enabled: false
  traefik:
    enabled: true
    hosts:
      - 'nodesampleapp-prod-live.ap-southeast-1.tidnex.com'
  replicas: 3
  command: 'node dist/src/server.js'
  env:
    CHAMBER_ENVIRONMENT_PREFIX: production/live
    SERVICE_NAME: 'nodesampleapp'
    TRACER_ENV: 'production'
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 400Mi
  livenessProbe:
    type: http
    port: 3000
    path: /healthcheck/liveness
  readinessProbe:
    type: http
    port: 3000
    path: /healthcheck/readiness
  service:
    port: 80
    targetPort: 3000
  autoscaling:
    enabled: true
    min: 3
    max: 6
    metrics:
      cpu:
        targetAverageUtilization: 80
      memory:
        targetAverageUtilization: 80

worker:
  enabled: false
  # runners:
  # - name: example
  #   command: "node dist/src/workers/example-worker.js"
  #   replicas: 1
  #   env:
  #     SERVICE_NAME: "nodesampleapp"
  #     TRACER_ENV: "production"
  #   resources:
  #     requests:
  #       cpu: 50m
  #       memory: 100Mi
  #     limits:
  #       cpu: 200m
  #       memory: 400Mi

cron:
  enabled: false
  # crons:
  # - name: example
  #   cron: '*/5 * * * *'
  #   command: "node dist/src/crons/example-cron.ts"
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
  #     limits:
  #       cpu: 300m
  #       memory: 400Mi
